[package]
name = "bevy_usd"
version = "0.1.0"
edition = "2024"


[dependencies]
bevy = "0.16.1"
pyo3 = { version = "0.26.0", features = ["auto-initialize"] }
smooth-bevy-cameras = "0.14.0"
triangulate = "0.2.0"

